[package]
name = "ex_11_ecs"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "11_ecs"
path = "src/main.rs"

[dependencies]
game-toolkit = { workspace = true, features = ["ecs"] }
env_logger = { workspace = true }
# The generated ECS code logs via tracing.
tracing = { workspace = true }

[build-dependencies]
sillyecs = { workspace = true }

[lints]
workspace = true
