[package]
name = "toolkit-prelude"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
toolkit-core   = { workspace = true }
toolkit-gfx    = { workspace = true }
toolkit-input  = { workspace = true }
toolkit-audio    = { workspace = true }
toolkit-assets   = { workspace = true }
toolkit-aseprite = { workspace = true, optional = true }
toolkit-ecs      = { workspace = true, optional = true }
toolkit-ui       = { workspace = true, optional = true }
winit            = { workspace = true }
anyhow           = { workspace = true }

[features]
default = []
ui = ["dep:toolkit-ui"]
aseprite = ["dep:toolkit-aseprite"]
ecs = ["dep:toolkit-ecs"]
synth = ["toolkit-audio/synth"]
vector = ["toolkit-gfx/vector"]

[lints]
workspace = true
