[package]
name = "ex_07_audio"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "07_audio"
path = "src/main.rs"

[dependencies]
game-toolkit-prelude = { workspace = true, features = ["synth"] }
env_logger = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
